# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eb03af6c426da0830a5f796e03e3f99b355d2479e7a9704f98179d2e0ee044208e51ffdfb21e4afef7a7b04ac399b24c52114da5f3ffb02e1f4eb956777b51b

test:
  secret_key_base: 9b97aaa4f47b2ba97bd503327ac7804d722135d606402bdbbaa60abeefe01f3ce5483d8db583341fe5817935644102f13acd291397e96824a27d2f3829d1cb6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
